version: "3.7"
services:
  webserver:
    build: app
    ports: 
      - 8077:80
    volumes:
      - ./app:/var/www/html/
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 8079:3306
    environment:
      MYSQL_ROOT_PASSWORD: inapple
    volumes:
      - php-volume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8078:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  php-volume:
