CREATE DATABASE IF NOT EXISTS caio;
USE caio;
CREATE TABLE teste (id MEDIUMINT NOT NULL AUTO_INCREMENT, nome CHAR(30) NOT NULL, PRIMARY KEY (id));
INSERT INTO teste (nome) VALUES ('caio'),('sergio');
